from bot.domain.entities import QuizQuestion

QUIZ_QUESTIONS: list[QuizQuestion] = [
    QuizQuestion(
        id=1,
        question="Who is considered the founder of modern Russian literature?",
        options=["Mikhail Lermontov", "Alexander Pushkin", "Nikolai Gogol", "Vasily Zhukovsky"],
        correct_index=1,
        explanation="Pushkin created the modern Russian literary language and established national literature on a European level.",
    ),
    QuizQuestion(
        id=2,
        question="Which work is called 'an encyclopedia of Russian life'?",
        options=["War and Peace", "Dead Souls", "Eugene Onegin", "Fathers and Sons"],
        correct_index=2,
        explanation="Belinsky called 'Eugene Onegin' an encyclopedia of Russian life because it captured all aspects of Russian society.",
    ),
    QuizQuestion(
        id=3,
        question="What literary type did Lermontov create in 'A Hero of Our Time'?",
        options=["The new person", "The superfluous man (Pechorin)", "The little man", "The nihilist"],
        correct_index=1,
        explanation="Pechorin is the first psychologically complex 'superfluous man' in Russian prose.",
    ),
    QuizQuestion(
        id=4,
        question="What phrase became proverbial thanks to Gogol?",
        options=[
            "'All happy families are alike'",
            "'We all came out from under Gogol's overcoat'",
            "'The dead have no shame'",
            "'A nose walked out on its own'",
        ],
        correct_index=1,
        explanation="Dostoevsky said 'We all came out from under Gogol's overcoat,' meaning Gogol's influence on all subsequent Russian prose.",
    ),
    QuizQuestion(
        id=5,
        question="What word did Turgenev's 'Fathers and Sons' introduce into Russian?",
        options=["Intelligentsia", "Nihilism", "Oblomovism", "Utilitarianism"],
        correct_index=1,
        explanation="Bazarov's philosophy of nihilism — rejecting all established values — gave the Russian language the word 'nihilism.'",
    ),
    QuizQuestion(
        id=6,
        question="What is 'Oblomovism'?",
        options=[
            "A type of political activism",
            "Noble apathy and inability to act",
            "A poetic movement",
            "A philosophy of progress",
        ],
        correct_index=1,
        explanation="Oblomovism — from Goncharov's novel — describes noble apathy, the inability to act, and passive withdrawal from life.",
    ),
    QuizQuestion(
        id=7,
        question="Which novel explored the psychology of a murderer?",
        options=["The Idiot", "Demons", "Crime and Punishment", "The Brothers Karamazov"],
        correct_index=2,
        explanation="'Crime and Punishment' is Dostoevsky's psychological study of Raskolnikov's mind after committing murder.",
    ),
    QuizQuestion(
        id=8,
        question="Why was Tolstoy excommunicated?",
        options=[
            "He was a revolutionary",
            "He criticized the Orthodox Church",
            "He supported the Decembrists",
            "He wrote 'Anna Karenina'",
        ],
        correct_index=1,
        explanation="Tolstoy wrote a letter to the Tsar calling the Orthodox Church corrupt, and was excommunicated in response.",
    ),
    QuizQuestion(
        id=9,
        question="What did Nekrasov bring to Russian poetry?",
        options=[
            "Romantic landscapes",
            "The voice of the people and peasant suffering",
            "Religious mysticism",
            "Urban futurism",
        ],
        correct_index=1,
        explanation="Nekrasov was the first major poet to make peasant suffering and the voice of the people his central subject.",
    ),
    QuizQuestion(
        id=10,
        question="What social class did Ostrovsky bring to the Russian stage?",
        options=["The nobility", "The military", "The Moscow merchant class", "The clergy"],
        correct_index=2,
        explanation="Ostrovsky depicted the Moscow merchant class — a social stratum that had been invisible in Russian drama before.",
    ),
    QuizQuestion(
        id=11,
        question="What is Aesopian language?",
        options=[
            "Writing in ancient Greek",
            "Allegorical satire that avoids censorship",
            "A type of free verse",
            "Writing for children",
        ],
        correct_index=1,
        explanation="Aesopian language — named after Aesop's fables — is allegorical writing that criticizes the regime while avoiding censorship. Saltykov-Shchedrin was its master.",
    ),
    QuizQuestion(
        id=12,
        question="What made Chernyshevsky's 'What Is to Be Done?' so influential?",
        options=[
            "Its beautiful prose",
            "Its model of the rational 'new person'",
            "Its criticism of the Tsar",
            "Its love story",
        ],
        correct_index=1,
        explanation="'What Is to Be Done?' provided a model of the 'new person' — rational, self-sacrificing, and committed to social change. Lenin called it life-changing.",
    ),
    QuizQuestion(
        id=13,
        question="What did Chekhov change in drama?",
        options=[
            "He added more soliloquies",
            "He replaced direct conflict with subtext",
            "He wrote only comedies",
            "He removed all stage directions",
        ],
        correct_index=1,
        explanation="Chekhov replaced direct conflict and moralizing with subtext — what characters don't say matters more than what they do.",
    ),
    QuizQuestion(
        id=14,
        question="What social class did Gorky bring into literature?",
        options=[
            "The nobility",
            "The clergy",
            "The lower classes — tramps, workers, the urban poor",
            "The intelligentsia",
        ],
        correct_index=2,
        explanation="Gorky brought the voices of the lower classes — tramps, workers, and the urban poor — into Russian literature.",
    ),
    QuizQuestion(
        id=15,
        question="What makes Blok's 'The Twelve' so controversial?",
        options=[
            "Its anti-religious message",
            "Jesus Christ leading Bolshevik Red Guards",
            "Its attack on the Tsar",
            "Its use of profanity",
        ],
        correct_index=1,
        explanation="'The Twelve' ends with Jesus Christ leading a band of Red Guards through a blizzard — a shocking fusion of revolution and religion.",
    ),
    QuizQuestion(
        id=16,
        question="How did Akhmatova write 'Requiem' under the terror?",
        options=[
            "She published it abroad",
            "She memorized it and had friends memorize it",
            "She hid it in a safe",
            "She wrote it in code",
        ],
        correct_index=1,
        explanation="Akhmatova memorized 'Requiem' and had friends memorize the lines, then burned the paper — the poem survived only in human memory.",
    ),
    QuizQuestion(
        id=17,
        question="What did Acmeism propose instead of Symbolism?",
        options=[
            "More mysticism",
            "Clarity, precision, and the material world",
            "Political engagement",
            "Religious themes",
        ],
        correct_index=1,
        explanation="Acmeism, founded by Gumilev, replaced Symbolist mystery with clarity, precision, and celebration of the material world.",
    ),
    QuizQuestion(
        id=18,
        question="What was Mayakovsky's 'stepladder' verse?",
        options=[
            "A visual staircase arrangement of lines creating new rhythm",
            "A type of sonnet",
            "Verse about architecture",
            "Poetry written on actual stairs",
        ],
        correct_index=0,
        explanation="Mayakovsky's 'stepladder' verse arranged lines in a staircase pattern, forcing a new rhythm and breaking traditional Russian verse.",
    ),
    QuizQuestion(
        id=19,
        question="Why is Bely's 'Petersburg' compared to Joyce's 'Ulysses'?",
        options=[
            "Both are set in capital cities",
            "Both are radical experiments with language and narrative",
            "Both were written in the same year",
            "Both are about the same topic",
        ],
        correct_index=1,
        explanation="'Petersburg' and 'Ulysses' are both radical experiments with language, rhythm, and narrative that redefined what a novel could be.",
    ),
    QuizQuestion(
        id=20,
        question="What did Yesenin's poetry symbolize for Russia?",
        options=[
            "The industrial revolution",
            "The beauty and destruction of rural Russia",
            "The urban working class",
            "Military heroism",
        ],
        correct_index=1,
        explanation="Yesenin's poetry captured the beauty and destruction of rural Russia. His death became a symbol of the old village dying.",
    ),
    QuizQuestion(
        id=21,
        question="Which historical event directly inspired Tolstoy's 'War and Peace'?",
        options=[
            "The Decembrist revolt",
            "The Patriotic War of 1812",
            "The emancipation of the serfs",
            "The Crimean War",
        ],
        correct_index=1,
        explanation="'War and Peace' is centered on the Patriotic War of 1812 and Napoleon's invasion of Russia.",
    ),
    QuizQuestion(
        id=22,
        question="What happened on 'Bloody Sunday' in 1905?",
        options=[
            "The Tsar was assassinated",
            "Troops fired on a peaceful workers' demonstration",
            "A factory burned down",
            "The Duma was dissolved",
        ],
        correct_index=1,
        explanation="On January 9, 1905, troops fired on a peaceful workers' demonstration in Saint Petersburg, triggering the First Russian Revolution.",
    ),
    QuizQuestion(
        id=23,
        question="What was tragically ironic about Alexander II's assassination?",
        options=[
            "He was killed by his own guards",
            "He was killed on the day he approved constitutional reform",
            "He survived the first bomb but was killed by the second",
            "He had already abdicated",
        ],
        correct_index=1,
        explanation="Alexander II was killed on the very day he had approved a plan for constitutional reform — the reform that might have prevented further revolution.",
    ),
    QuizQuestion(
        id=24,
        question="What was 'going to the people' (narodnichestvo)?",
        options=[
            "Peasants moving to cities",
            "Students going to live among peasants to educate them",
            "A literary movement",
            "A military campaign",
        ],
        correct_index=1,
        explanation="In 1874, thousands of students went to live among the peasants, hoping to educate them — but the peasants mostly turned them in to the police.",
    ),
    QuizQuestion(
        id=25,
        question="What did the 1917 revolutions mean for the Silver Age?",
        options=[
            "They had no effect on literature",
            "They ended it — the world of Blok and Akhmatova was destroyed",
            "They started the Silver Age",
            "They created a new literary movement",
        ],
        correct_index=1,
        explanation="The 1917 revolutions ended the Silver Age. The world those poets wrote about was destroyed — some emigrated, some were silenced, some tried to adapt.",
    ),
]
